name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch Sources
      uses: actions/checkout@v2
    - name: Run through C-Util CI
      uses: converse1/automation/src/ci-c-util@master
      with:
        m32: 1
        valgrind: 0
